### ISSUE TITLE
dynamic window size when text overflows outside of normal bounds

### ISSUE THREAD

**Issue by xNasuni** [o7Moon/minicalc#25]
i don't know if this is neccessary but if i calculate something like `8/7` the text overflows outside of the window (shown below) and i think that you could make the window size lengthened so it can fit all the text like calculating the font width with kerning and stuff. i suck at explaining stuff but **TLDR; text overflows outside of the window and window could maybe automatically resize itself to fit the text**
![image](https://github.com/o7Moon/minicalc/assets/62818119/a0edda1c-cfd3-4eb4-8972-023a4709237e)
![image](https://github.com/o7Moon/minicalc/assets/62818119/094e938e-e2c9-460e-b753-7f9e1a05185e)

**Comment by o7Moon** [comment]
ill make this a config option you can turn on in 0.3
